### ISSUE TITLE
kanboard_TaskVote - Follow up

### ISSUE THREAD

**Issue by RRRRoger** [Busfreak/kanboard_TaskVote#1]
If i understand correctly, we should continue posting here instead of there: https://github.com/kanboard/kanboard/issues/3053#issuecomment-293215759

Well this sounds promising!

I don't think tracking who has voted is necessary, it might even be better if it's anonymous.
I see the voting as an indicator of what the majority thinks of some polarizing issue, so the more feedback the better. 
Tracking and making public the preferences of people who voted might prevent them from expressing their very intimate and real opinion.  

I see the sorting as complementary to the voting feature but i think Kanboard would definitely benefit from some sorting options.  
Sorting tasks manually works for now, it can just be time consuming when there is hundreds of tasks to move around. 

@whinote, does this makes sense to you?

**Comment by whinote** [comment]
It is completely ok if we do not display who has voted in the task so it is anonymous in that aspect but we do need to make it so that a user cannot vote more than once. Making the votes anonymous to the other users might encourage users to get behind some projects that might not be viewed as priority by some. As long as each user only gets one vote and there is some way we can see that data as the admins, even if it is searching the database from the CLI. We don't want users / team members inflating votes. Sorting would be helpful but not necessary for what we will be using this for. We have several different task boards for individual groups so we don't ever have that many tasks displayed and it is easy enough for us to manually sort them for now.


________________________________

**Comment by Busfreak** [comment]
Hi!
give it a try:
https://github.com/Busfreak/kanboard_TaskVote/releases/tag/v.0.0.1
Sorting is in the dropdown at top of a column, but also automatically after voting.

**Comment by RRRRoger** [comment]
Iyo,

Hey that looks pretty cool!

The sorting feature is nice but since there is only the "sort by voting" for now and it's not possible to turn it off, the sorting is now determined only by the votes.
I've tried pressing the "sort by voting" dropdown but it sent me to this message:
![sortbyvoting](https://cloud.githubusercontent.com/assets/26545297/24927796/306d9218-1ece-11e7-9364-64be6a35919d.jpg)
![pagenotfound](https://cloud.githubusercontent.com/assets/26545297/24927774/20ee111e-1ece-11e7-911c-3362a4e608fa.jpg)

I normally sort my columns manually by color but the TaskVote now forces sorting by vote as soon as one task is being voted ruining my precious color sorting (sadface) .
I'm still convinced the sort by voting could be very useful but it shouldn't be the only way, nor the defaut way of sorting things.


The single vote per user feature is very cool but could the user change his vote from upvote to downvote?
Right now it's permanent and it could be problematic in those scenarios:

- A user made a mistake, downvoted instead of upvoting. He can't go back.

- A task that was once upvoted by a user changed from it's main purpose or became irrelevant for him and he now wants to downvote it, but he can't.

Other than that, thank's alot, it seems like it's a feature we will use!

**Comment by Busfreak** [comment]
Hi @RRRRoger 
sorting is permanent, the task's position is stored in the database. It is not (yet?) possible to sort temporarily.
In the Kanban method the position of a task in a column represents it's significance, either manualy or by votes, so temporarily ordering actually doesn't make sense.
The question is, should the sorting be done with every vote, only by an admin / manager, or not at all.
We also could think about voting (and sorting) only in specific columns.

The method for sorting is the same in automatic action and in the dropdown. Can you write down the URL from the board view before pressing "sort by voting", the URL from the dropdown link and the URL from error page to find the possible error?

One vote per user / task does not imply that the user can change his opinion. Is this really necessary?

**Comment by RRRRoger** [comment]
Sorry for not replying earlier, i was crazy busy yesterday.

I might start a separate topic where i would propose the "Sorting Feature" i'm thinking of, but for now, for me. the "Sorting by vote" is more harmful than helpful.
@whinote said he didn't need sorting by vote so I suggest that for now, the sorting should't be done at all and we will keep sorting manually.

For the URL of the error message i'm not sure the company i'm working on would let me put it public, i need to ask.

**Comment by Busfreak** [comment]
I don't need the whole URL. Just the parameters.

**Comment by RRRRoger** [comment]
I'm not sure thats what you're looking for but it's the url that i get in my browser for the different pages.
I don't know how to get the one from the dropdown.

URL from the board:
?controller=BoardViewController&action=show&project_id=17
URL from the error page:
?controller=TaskVoteController&action=sort&plugin=taskVote&column_id=93

@Busfreak One vote per user / task does not imply that the user can change his opinion. Is this really necessary?
I think it is. Suppose one week someone thinks "washing the floor" is more important, he votes for it. 
Maybe next week we would prefer to "wash the dishes", he would remove he's upvote on the previous one cause it's not relevant for him anymore. 
It's just an example but i don't see anything wrong with it, except that i have no idea how to code it or how to make it work!

People still have only one vote per task but they can move it from Positive to Negative. I guess there would be an invisible "Neutral" vote if someone's downvoting an upvote and vice-versa.

**Comment by Busfreak** [comment]
The sorting function has been removed and users can change their opinion.
Have fun.
https://github.com/Busfreak/kanboard_TaskVote/releases/tag/v0.0.2

**Comment by RRRRoger** [comment]
That is pretty nice, we will start using it!

I hope @whinote likes it!
